name: Flink Deploy Test

on:
  push:
    branches:
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Flink JAR
        run: mvn clean package

      - name: Copy JAR to VM and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.UAT_VM_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /opt/deploy/flink
            cp ./build/libs/all-1.2.2.jar /opt/deploy/flink/
            cd /opt/deploy/flink
            chmod +x ci/deploy.sh
            ./ci/deploy.sh uat blue
