name: Flink Deploy Test

on:
  push:
    branches:
      - uat

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Flink JAR
        run: mvn clean package

      - name: List files
        run: ls -l ./target ./ci

      - name: Copy JAR and deploy script to VM
        run: |
          echo "${{ secrets.SSH_KEY }}" > temp_key.pem
          chmod 600 temp_key.pem
          scp -i temp_key.pem -P 2222 target/all-1.2.2.jar ci/deploy.sh \
            ${{ secrets.SSH_USER }}@host.docker.internal:/opt/deploy/flink/

      - name: Run deploy script on VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: host.docker.internal
          port: 2222
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/deploy/flink
            chmod +x deploy.sh
            ./deploy.sh uat blue